### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by frenzymadness** [lachhebo/pyclustertend#2]
Hello.

I'd like to use your package to show the Hopkins test to my students but it, unfortunately, does not work with the latest scikit-learn. The problem is the old name for `calinski_harabaz_score` which has been removed from the latest sklearn.

I see that it's already fixed in the master so could you please release version 1.4.9 to PyPI?

Thanks a lot and have a nice day.

**Comment by lachhebo** [comment]
thanks for the tip :) 

I hope you will have the opportunity to present this package to your student.
