### ISSUE TITLE
AttributeError: module 'sklearn.metrics._dist_metrics' has no attribute 'DistanceMetric32'

### ISSUE THREAD

**Issue by mpetruc** [lachhebo/pyclustertend#28]
just installed pyclustertend  1.8.2 using pip as per instructions.
when trying to import the library i get the error above.
pyclustertend   by default installs/upgrades scikit-learn 1.2.2. I downgraded to 1.1.2, but that didn't solve the problem. 
Do you have any recommendations for how to make it work?
thanks a lot

**Comment by lachhebo** [comment]
hi, i just made an update that should fix the issue
