### ISSUE TITLE
Error when import pyclustertend

### ISSUE THREAD

**Issue by KumawatP** [lachhebo/pyclustertend#3]
I installed pyclustertend using pip install and also using conda install and many other ways, but is always giving the same error while running the code as
code=
import sys
import os.path
import os
import pyclustertend
from sklearn import datasets
from pyclustertend import vat
from sklearn.preprocessing import scale
X = scale(df3)
vat(X)

Error=
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-894-a4747870a2da> in <module>
      2 import os.path
      3 import os
----> 4 import pyclustertend
      5 from sklearn import datasets
      6 from pyclustertend import vat

ModuleNotFoundError: No module named 'pyclustertend'

I tried many ways as given below:-

way 1# 
(base) MacBook:~ pinky$ python -m pip install pyclustertend
Requirement already satisfied: pyclustertend in /opt/anaconda3/lib/python3.7/site-packages/pyclustertend-1.4.9-py3.7.egg (1.4.9)

way 2# 
(base) MacBook:~ pinky$ pip3 install pyclustertend
Collecting pyclustertend
  Using cached pyclustertend-1.4.9-py3-none-any.whl (9.8 kB)
Installing collected packages: pyclustertend
Successfully installed pyclustertend-1.4.9

way 3#
(base) MacBook:~ pinky$ conda install pyclustertend
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pyclustertend

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

way4#
(base) MacBook:~ pinky$ pip install pyclustertend==1.4.9
Requirement already satisfied: pyclustertend==1.4.9 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (1.4.9)

But always getting  error while ruuning in jupyter notebook as
ModuleNotFoundError: No module named 'pyclustertend'

Does anyone can help me to solve the problem, I am not very efficient in python, Thanks a lot in advance.

**Comment by lachhebo** [comment]
Hello, 

you installed pyclustertend in your conda environment but you're jupyter notebook is probably not using it.

**Comment by KumawatP** [comment]
Thank you so much lachhebo for quick reply.

Is there anyway to solve this issue?

**Comment by lachhebo** [comment]
you should probably install nb_conda on your environment and select the correct env in your notebook
