### ISSUE TITLE
hopkins docs

### ISSUE THREAD

**Issue by schusterc** [lachhebo/pyclustertend#4]
Hello :)

I found some contradictory information on the hopkins test on https://pyclustertend.readthedocs.io/en/latest/

On the top it says:
If the test is positve, (an hopkins score which tends to 0) it means that clustering is useless for the dataset.

In the API section it says:
A score between 0 and 1, a score around 0.5 express no clusterability and a score tending to 0 express a high cluster tendency.

**Comment by lachhebo** [comment]
Hello, 

That is definetely an error on the documentation, the hopkins score indicate a potential clusterability when the score tend to 0 and the clustering is generally not pertinent when the score is above 0.20.

**Comment by bdalal** [comment]
According to [wikipedia](https://en.wikipedia.org/wiki/Hopkins_statistic), seems like this definition is backward. An H-score closer to 1 would indicate a high potential for clustering.

**Comment by bonehead** [comment]
I can see that the definition is still contradictory to both [Wikipedia](https://en.wikipedia.org/wiki/Hopkins_statistic) as well as the [reference](http://www.sthda.com/english/wiki/print.php?id=238) in [Pyclusterend docs](https://pyclustertend.readthedocs.io/en/latest/).
Both Wikipedia and the reference indicate that a value closer to 1 indicate presence of clusters.
